config/routes.rb
Rails.application.routes.draw do
  get 'projects/show'

  get 'tag_cloud/index'
  
  get 'navigator/navigator'

  get 'projects/table'

	get 'projects/cluster', to: 'projects#cluster'

  get '/projects/:id', to: 'projects#show'
  
  root 'navigator#navigator'

  get  '/projects/:id/en', to: 'projects#show_en'

  get 'searchid/searchid'
end

app/controllers/navigator_controller.rb
class NavigatorController < ApplicationController
    cattr_accessor :cmembers
    require 'cluster/headlines'
    @@cmembers = [[], [], [], []]
    @@tag_array = [{}, {}, {}, {}]
    def self.tag_array
        @@tag_array
    end

    def self.cmembers
        @@cmembers
    end

    def navigator
        @size = 400
        @@tag_array = []
        params[:view_projects] ||= "all"
        params[:n_cluster] ||= 6
        params[:keep_cluster] ||= "false"
        k  = params[:n_cluster].to_i
        temp = @@cmembers.length
        if k < temp
            for i in 1..(temp - k)
                @@cmembers.pop
            end
        end
        begin
            c = Clusterizer.new(params[:n_cluster].to_i)
            if params[:view_projects] == "all"
                clusters = CGroup.where("size = ?", k).first
                if clusters != nil
                    clusters.clusterIdsArray.each_with_index do |id, index|
                        cluster = Cluster.find(id)
                        #puts cluster
                        #cluster.each_with_index do |tag, index| 
                        @@tag_array << cluster.tags
                        @@cmembers[index] = cluster.projectIdsArray
                      #end
                    end
                    groups = []
                else
                  groups, @@cmembers = c.clusters(params[:view_projects])
                end
                #params[:view_projects] = ""
            else
                if params[:keep_cluster] == "true"
                    aux = @@cmembers.flatten
                    groups, @@cmembers = c.clusters (aux)
                else
                    groups, @@cmembers = c.clusters (@@cmembers[params[:view_projects].to_i])
                end
                @@view_paths ||= params[:view_projects].to_i
                #if @@view_paths <= params[:view_projects].to_i
                @@view_paths = params[:view_projects].to_i
                #else
                 #   params[:view_projects] = ""
                 #   @@view_paths = nil
                 #   redirect_to navigator_navigator_path
                #end
            end
            groups.each do |tag|
                array = []
                tag.each do |key, value|
                    array << {:text => key.to_s, :weight => value.to_s}
                end
                @@tag_array << array
            end
            @cmembers = @@cmembers
            @tag_array = @@tag_array
        rescue
            params[:n_cluster].to_i.times do
                @@tag_array << {}
            end
        end
    end
end

app/helpers/navigator_helper.rb
module NavigatorHelper
end

app/views/navigator/navigator.html.haml
%script{:type=>"text/javascript"}
  var array = new Array();
  var i = 0;
  -@tag_array.each do |tag|
    array.push(#{raw tag.to_json});
    $(function() {
    / / When DOM is ready, select the container element and call
    // the jQCloud method, passing the array of words as the first argument.
    $("#tag_" + i).empty();
    $("#tag_" + i).jQCloud(array[i], {
    fontSize: {
    from: 0.02,
    to: 0.02
    }
    });
    i++;
    });
-@size *= @tag_array.length / 2
%div.principal
  %h4.page-title Índice de projetos agrupados por assunto
  %div.container{:style=>"text-align: left; border-collapse: separate; width: 100%; height: auto;"}
    -@index = 0
    -@tag_array.in_groups_of(3).each do |group|
      %div.row{:style => "height: auto; padding-top: 10px;"}
        -group.each do |tag|
          %div.col-md-4.col-sd-4.col-xs-4{:style=>"width: 33%; height: auto; background-color:#FBF6F1;padding-left: 3%"}
            %div.row{:id => "tag_#{@index}", :style => "height: 300px;"}
            -unless @cmembers[@index].nil?
              %div.row{:style=>"text-align: center;"}
                =link_to (projects_cluster_path(params.merge(id: @index))) do
                  %div.botao.col-md-6.col-sd-6.col-xs-12{:style => "float: left; height auto;"}= "Mostrar " + @cmembers[@index].count.to_s + " Projetos"
                =link_to (navigator_navigator_path(params.merge(view_projects: @index.to_s, n_cluster: params[:n_cluster], keep_cluster: "false"))) do
                  %div.botao.col-md-6.col-sd-6.col-xs-12{:style => "float: right; height auto;"} Ver Subgrupos
                -@index = @index + 1
    %div.row{:style => "padding-top: 10px;"}
      =form_tag({:action => 'navigator', view_projects: params[:view_projects]}, :method => :get) do
        %label{:for => 'n_cluster'} Redefinir número de Clusters
        = number_field_tag(:n_cluster, params[:n_cluster], {:min => 1, :max => 10})
        = hidden_field_tag(:view_projects, params[:view_projects])
        = hidden_field_tag(:keep_cluster, "true")
        = submit_tag 'Atualizar'
      = form_tag(searchid_searchid_path, :method => "get", id: "search-form") do
        = text_field_tag :search, params[:search], placeholder: "Search ID"
        = submit_tag "Search", :name => nil